"""Add gender to puppy

Revision ID: 04f223ec3788
Revises: 33b46d2b16b4
Create Date: 2026-03-10 13:41:34.051942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f223ec3788'
down_revision = '33b46d2b16b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
