"""Add is_guardian field to Parent model

Revision ID: 0f0e1671ce93
Revises: d0df36c1ff04
Create Date: 2025-07-28 14:05:11.523471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0e1671ce93'
down_revision = 'd0df36c1ff04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guardian', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_column('is_guardian')

    # ### end Alembic commands ###
