"""Add editable text fields to HeroSection model

Revision ID: 1febda415d98
Revises: 0f0e1671ce93
Create Date: 2025-07-30 15:10:36.382783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1febda415d98'
down_revision = '0f0e1671ce93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('scroll_text_main', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('scroll_text_secondary', sa.String(length=100), nullable=True))
        batch_op.alter_column('subtitle',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('cta_text')
        batch_op.drop_column('title')
        batch_op.drop_column('cta_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
        batch_op.add_column(sa.Column('cta_text', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.alter_column('subtitle',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               existing_nullable=True)
        batch_op.drop_column('scroll_text_secondary')
        batch_op.drop_column('scroll_text_main')
        batch_op.drop_column('description')
        batch_op.drop_column('main_title')

    # ### end Alembic commands ###
