"""Rename image URL columns to S3 key columns

Revision ID: 23d27b4ee186
Revises: 221e7634c086
Create Date: 2025-08-03 12:55:05.969288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23d27b4ee186'
down_revision = '221e7634c086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_s3_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_s3_key_small', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_s3_key_medium', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_s3_key_large', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url_medium')
        batch_op.drop_column('image_url_large')
        batch_op.drop_column('image_url_small')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_s3_key', sa.String(length=255), nullable=False))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('hero_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_s3_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_s3_key_small', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_s3_key_medium', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_s3_key_large', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url_large')
        batch_op.drop_column('image_url_small')
        batch_op.drop_column('image_url')
        batch_op.drop_column('image_url_medium')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_s3_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_s3_key_small', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_s3_key_medium', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_s3_key_large', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_s3_key_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_s3_key_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_s3_key_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_s3_key_4', sa.String(length=255), nullable=True))
        batch_op.drop_column('main_image_url')
        batch_op.drop_column('main_image_url_medium')
        batch_op.drop_column('alternate_image_url_3')
        batch_op.drop_column('alternate_image_url_4')
        batch_op.drop_column('main_image_url_large')
        batch_op.drop_column('main_image_url_small')
        batch_op.drop_column('alternate_image_url_2')
        batch_op.drop_column('alternate_image_url_1')

    with op.batch_alter_table('parent_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_s3_key', sa.String(length=255), nullable=False))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_s3_key', sa.String(length=255), nullable=True))
        batch_op.drop_column('main_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('main_image_s3_key')

    with op.batch_alter_table('parent_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('image_s3_key')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternate_image_url_1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_url_2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_url_small', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_url_large', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_url_4', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_url_3', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_url_medium', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('alternate_image_s3_key_4')
        batch_op.drop_column('alternate_image_s3_key_3')
        batch_op.drop_column('alternate_image_s3_key_2')
        batch_op.drop_column('alternate_image_s3_key_1')
        batch_op.drop_column('main_image_s3_key_large')
        batch_op.drop_column('main_image_s3_key_medium')
        batch_op.drop_column('main_image_s3_key_small')
        batch_op.drop_column('main_image_s3_key')

    with op.batch_alter_table('hero_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url_medium', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_small', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_large', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('image_s3_key_large')
        batch_op.drop_column('image_s3_key_medium')
        batch_op.drop_column('image_s3_key_small')
        batch_op.drop_column('image_s3_key')

    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('image_s3_key')

    with op.batch_alter_table('about_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_small', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_large', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_medium', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('image_s3_key_large')
        batch_op.drop_column('image_s3_key_medium')
        batch_op.drop_column('image_s3_key_small')
        batch_op.drop_column('image_s3_key')

    # ### end Alembic commands ###
