"""empty message

Revision ID: 28a0bc71e1a4
Revises: 973b3d9af33b
Create Date: 2026-02-25 20:09:29.323531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a0bc71e1a4'
down_revision = '973b3d9af33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents_page_intro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('image_s3_key', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_small', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_medium', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_large', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parents_page_intro')
    # ### end Alembic commands ###
