"""add upcoming litter stage and expected birth date

Revision ID: 2f45a29bb9f6
Revises: 04f223ec3788
Create Date: 2026-03-13 15:54:53.435663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f45a29bb9f6'
down_revision = '04f223ec3788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_birth_date', sa.Date(), nullable=True))
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('expected_birth_date')

    # ### end Alembic commands ###
