"""Add review_images table 1

Revision ID: 3173f8db5399
Revises: f37664990918
Create Date: 2026-03-02 14:57:34.228267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3173f8db5399'
down_revision = 'f37664990918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_review_sort_order'), ['sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sort_order'))
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
