"""Add status_mode to litter

Revision ID: 33b46d2b16b4
Revises: 3173f8db5399
Create Date: 2026-03-02 15:59:49.540707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b46d2b16b4'
down_revision = '3173f8db5399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_mode', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_litter_status_mode'), ['status_mode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litter_status_mode'))
        batch_op.drop_column('status_mode')

    # ### end Alembic commands ###
