"""Add AnnouncementBanner model

Revision ID: 3d1c2d436dc1
Revises: 1febda415d98
Create Date: 2025-07-30 15:42:35.962284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1c2d436dc1'
down_revision = '1febda415d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('main_text', sa.String(length=200), nullable=True),
    sa.Column('sub_text', sa.String(length=300), nullable=True),
    sa.Column('button_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement_banner')
    # ### end Alembic commands ###
