"""Add Breed model and relationships

Revision ID: 4e738c6976f4
Revises: 23d27b4ee186
Create Date: 2025-09-23 15:05:11.523471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e738c6976f4'
down_revision = '23d27b4ee186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_parent_breed', 'breed', ['breed_id'], ['id'])
        batch_op.drop_column('breed')

    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_puppy_breed', 'breed', ['breed_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.drop_constraint('fk_puppy_breed', type_='foreignkey')
        batch_op.drop_column('breed_id')

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_parent_breed', type_='foreignkey')
        batch_op.drop_column('breed_id')

    op.drop_table('breed')
    # ### end Alembic commands ###