"""Add is_active to ParentsPageIntro

Revision ID: 718e75299c63
Revises: 28a0bc71e1a4
Create Date: 2026-02-26 14:38:17.606775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718e75299c63'
down_revision = '28a0bc71e1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents_page_intro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents_page_intro', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
