"""Add litter main image

Revision ID: 973b3d9af33b
Revises: cf611088c530
Create Date: 2026-02-22 13:19:49.983322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973b3d9af33b'
down_revision = 'cf611088c530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_s3_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.drop_column('main_image_s3_key')

    # ### end Alembic commands ###
