"""Initial schema with Litter architecture

Revision ID: ad4e9a964d55
Revises: 
Create Date: 2026-02-18 14:40:07.485741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4e9a964d55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('image_s3_key', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_small', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_medium', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_large', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_s3_key', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_title', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('scroll_text_main', sa.String(length=100), nullable=True),
    sa.Column('scroll_text_secondary', sa.String(length=100), nullable=True),
    sa.Column('image_s3_key', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_small', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_medium', sa.String(length=255), nullable=True),
    sa.Column('image_s3_key_large', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('DAD', 'MOM', name='parentrole'), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_guardian', sa.Boolean(), nullable=False),
    sa.Column('main_image_s3_key', sa.String(length=255), nullable=True),
    sa.Column('main_image_s3_key_small', sa.String(length=255), nullable=True),
    sa.Column('main_image_s3_key_medium', sa.String(length=255), nullable=True),
    sa.Column('main_image_s3_key_large', sa.String(length=255), nullable=True),
    sa.Column('alternate_image_s3_key_1', sa.String(length=255), nullable=True),
    sa.Column('alternate_image_s3_key_2', sa.String(length=255), nullable=True),
    sa.Column('alternate_image_s3_key_3', sa.String(length=255), nullable=True),
    sa.Column('alternate_image_s3_key_4', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('testimonial_text', sa.Text(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('social_facebook_url', sa.String(length=255), nullable=True),
    sa.Column('social_instagram_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('litter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mom_id', sa.Integer(), nullable=False),
    sa.Column('dad_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('breed_name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_weight', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['dad_id'], ['parent.id'], ),
    sa.ForeignKeyConstraint(['mom_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('image_s3_key', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puppy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coat', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', name='puppystatus'), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('main_image_s3_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('main_text', sa.String(length=200), nullable=True),
    sa.Column('sub_text', sa.String(length=300), nullable=True),
    sa.Column('button_text', sa.String(length=50), nullable=True),
    sa.Column('featured_puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['featured_puppy_id'], ['puppy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement_banner')
    op.drop_table('puppy')
    op.drop_table('parent_image')
    op.drop_table('litter')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('site_details')
    op.drop_table('review')
    op.drop_table('parent')
    op.drop_table('hero_section')
    op.drop_table('gallery_image')
    op.drop_table('about_section')
    # ### end Alembic commands ###
