"""Announcement banner uses featured_litter

Revision ID: cf611088c530
Revises: ad4e9a964d55
Create Date: 2026-02-18 16:12:28.426590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf611088c530'
down_revision = 'ad4e9a964d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_litter_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('announcement_banner_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'litter', ['featured_litter_id'], ['id'])
        batch_op.drop_column('featured_puppy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_puppy_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('announcement_banner_ibfk_1'), 'puppy', ['featured_puppy_id'], ['id'])
        batch_op.drop_column('featured_litter_id')

    # ### end Alembic commands ###
