"""Add responsive image fields to Parent and site models

Revision ID: d0df36c1ff04
Revises: fc85b3998d19
Create Date: 2025-07-23 16:47:01.976049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0df36c1ff04'
down_revision = 'fc85b3998d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url_small', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_medium', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_large', sa.String(length=255), nullable=True))

    with op.batch_alter_table('hero_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url_small', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_medium', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url_large', sa.String(length=255), nullable=True))

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_url_small', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_url_medium', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_url_large', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_column('main_image_url_large')
        batch_op.drop_column('main_image_url_medium')
        batch_op.drop_column('main_image_url_small')

    with op.batch_alter_table('hero_section', schema=None) as batch_op:
        batch_op.drop_column('image_url_large')
        batch_op.drop_column('image_url_medium')
        batch_op.drop_column('image_url_small')

    with op.batch_alter_table('about_section', schema=None) as batch_op:
        batch_op.drop_column('image_url_large')
        batch_op.drop_column('image_url_medium')
        batch_op.drop_column('image_url_small')

    # ### end Alembic commands ###
