"""Add review_images table

Revision ID: f37664990918
Revises: 718e75299c63
Create Date: 2026-03-02 14:03:29.959791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37664990918'
down_revision = '718e75299c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_images_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_images_sort_order'), ['sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_images_sort_order'))
        batch_op.drop_index(batch_op.f('ix_review_images_review_id'))

    op.drop_table('review_images')
    # ### end Alembic commands ###
