"""Add alternate image URLs to Parent model

Revision ID: fc85b3998d19
Revises: 
Create Date: 2025-07-23 14:00:09.369674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc85b3998d19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonial')
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternate_image_url_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_url_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_url_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('alternate_image_url_4', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_column('alternate_image_url_4')
        batch_op.drop_column('alternate_image_url_3')
        batch_op.drop_column('alternate_image_url_2')
        batch_op.drop_column('alternate_image_url_1')

    op.create_table('testimonial',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('testimonial_text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('is_featured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
